//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieApp1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities7 : DbContext
    {
        public Entities7()
            : base("name=Entities7")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actor> Actors { get; set; }
        public virtual DbSet<MovieActor> MovieActors { get; set; }
        public virtual DbSet<MovieBooking> MovieBookings { get; set; }
        public virtual DbSet<Movy> Movies { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Theater> Theaters { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<vMovieActor> vMovieActors { get; set; }
        public virtual DbSet<vMovieBook> vMovieBooks { get; set; }
        public virtual DbSet<vMovieDetail> vMovieDetails { get; set; }
    }
}
