//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieApp1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Theater
    {
        public int TheaterId { get; set; }
        public System.DateTimeOffset ShowTime { get; set; }
        public int Price { get; set; }
    }
}
