//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieApp1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vMovieDetail
    {
        public string MovieName { get; set; }
        public int MovieId { get; set; }
        public int ActorId { get; set; }
        public string ActorName { get; set; }
        public string Rating { get; set; }
        public string Country { get; set; }
        public string Favourite { get; set; }
    }
}
